<a href="https://colab.research.google.com/github/Paoarlett10/Tarea2/blob/main/ejercicio25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Ejercicio 25.
Vazquez Jimenez Arlett Paola / 320162033

**a)  A = LLᵀ , L triangular inferior.**

In [69]:
# Importar librerías necesarias
import numpy as np
from numpy import linalg as LA

# Función de Sustitución hacia adelante (resolver Ly = b)
def SustDelante(L, b):
    x = np.zeros_like(b)          # Inicializamos el vector solución con ceros
    n = L.shape[0]                # Número de filas de L

    for i in range(n):            # Recorremos cada fila
        suma = 0.0
        for j in range(i):         # Calculamos la suma de los productos L[i,j] * x[j]
            suma += L[i, j] * x[j]
        x[i] = (b[i] - suma) / L[i, i]   # Despejamos x[i]

    return x

# Función de Sustitución hacia atrás (resolver Ux = y)
def SustAtras(U, y):
    x = np.zeros_like(y)          # Inicializamos el vector solución con ceros
    n = U.shape[0]                # Número de filas de U (matriz triangular superior)

    # Resolvemos emepzando de atras o abajo hacia arriba
    x[n-1] = y[n-1] / U[n-1, n-1]
    for i in range(n-2, -1, -1):
        suma = 0.0
        for j in range(i+1, n):    # Calculamos la suma de los productos U[i,j] * x[j]
            suma += U[i, j] * x[j]
        x[i] = (y[i] - suma) / U[i, i]

    return x

# Función para realizar la factorización de Cholesky clásica (A = LLᵀ)
def Cholesky(A):
    n = A.shape[0]                # Número de filas/columnas de A
    L = np.zeros_like(A)           # Inicializamos L como una matriz de ceros

    for i in range(n):             # Recorrer filas
        for j in range(i+1):       # Recorrer columnas hasta la diagonal
            if i == j:             # Diagonal principal
                suma = 0.0
                for k in range(i):
                    suma += L[i][k] * L[i][k]   # Suma de cuadrados de los elementos anteriores
                L[i][i] = np.sqrt(A[i][i] - suma)   # Fórmula de la diagonal
            else:                  # Parte inferior (debajo de la diagonal)
                suma = 0.0
                for k in range(j):
                    suma += L[i][k] * L[j][k]   # Producto de elementos correspondientes
                L[i][j] = (A[i][j] - suma) / L[j][j]  # Fórmula para los elementos debajo de la diagonal

    return L

# Función para resolver Ax = b usando la factorización de Cholesky
def SolveChol(A, b):
    L = Cholesky(A)               # Obtenemos L tal que A = LLᵀ
    y = SustDelante(L, b)          # Resolvemos Ly = b
    x = SustAtras(L.T, y)          # Resolvemos Lᵀx = y

    return x

# Definimos la matriz A y el vector b
A = np.array([[6.0, 15.0, 55.0],
              [15.0, 55.0, 225.0],
              [55.0, 225.0, 979.0]])
b = np.array([10., 20., 30.])

# Resolvemos el sistema
sol = SolveChol(A, b)

# Imprimimos la solución
print("Solución usando Cholesky LLᵀ")
print(sol)


Solución usando Cholesky LLᵀ
[-0.89285714  4.625      -0.98214286]


**b) A = LDLᵀ , L triangular inferior, D diagonal.**

In [70]:
# Función para realizar la factorización de Cholesky modificada (A = L D Lᵀ)
def Cholesky_LDLt(A):
    n = A.shape[0]
    L = np.eye(n)                   # Inicializamos L como matriz identidad
    D = np.zeros(n)                 # Inicializamos D como vector de ceros (será la diagonal)

    for i in range(n):
        # Calculamos el valor de D[i] (diagonal de D)
        suma_diagonal = sum(D[k] * (L[i, k]**2) for k in range(i))
        D[i] = A[i, i] - suma_diagonal

        # Calculamos los elementos debajo de la diagonal en L
        for j in range(i+1, n):
            suma_abajo = sum(D[k] * L[i, k] * L[j, k] for k in range(i))
            L[j, i] = (A[j, i] - suma_abajo) / D[i]

    return L, D

# Función para resolver el sistema Ax = b usando la factorización LDLᵀ
def Chol_LDLt(A, b):
    L, D = Cholesky_LDLt(A)          # Factorizamos A en L, D
    y = SustDelante(L, b)            # Resolvemos Ly = b (sustitución hacia adelante)
    z = y / D                        # Resolvemos Dz = y
    x = SustAtras(L.T, z)            # Resolvemos Lᵀx = z (sustitución hacia atrás)

    return x

# Calculamos la solución con LDLᵀ
sol2 = Chol_LDLt(A, b)

# Imprimimos la solución
print("Solución usando Cholesky LDLᵀ:")
print(sol2)


Solución usando Cholesky LDLᵀ:
[-0.89285714  4.625      -0.98214286]


**solucióin analítica**

In [71]:
y=LA.solve(A,b)
print("Solucion Analitica")
print(y)

Solucion Analitica
[-0.89285714  4.625      -0.98214286]
